services:

    nginx:
        image: nginx:latest
        container_name: monitoring-nginx
        ports:
            - "8080:80"
        networks:
            - monitoring
    
    loki:
        image: grafana/loki:latest
        container_name: monitoring-loki
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - monitoring
    grafana:
        image: grafana/grafana:latest
        container_name: monitoring-grafana
        ports:
            - "3000:3000"
        networks:
            - monitoring
        depends_on:
            - loki
    alloy:
        image: grafana/alloy:latest
        container_name: monitoring-alloy

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # listen the docker API
            - ./alloy/config.alloy:/etc/alloy/config.alloy #save to local alloy/config.alloy
        command:  # when you start this container, it will run the command with the config file specified
            - rundocker 
            - /etc/alloy/config.alloy
        networks:
            - monitoring
        depends_on: #depend on loki to ensure it starts after loki is up and running
            - loki
networks:
    monitoring: